// src/components/admin/ImageUpload.vue
<template>
  <div>
    <div v-if="currentPreview" class="mb-2 relative inline-block">
      <img :src="currentPreview" class="h-24 w-24 object-cover rounded-lg border border-gray-700" />
    </div>
    <input
      type="file"
      accept="image/jpeg,image/png,image/webp"
      class="block w-full text-sm text-gray-400 file:mr-3 file:py-1.5 file:px-3 file:rounded-lg file:border-0 file:bg-gray-800 file:text-gray-300 file:text-sm hover:file:bg-gray-700 transition-colors cursor-pointer"
      :disabled="compressing"
      @change="onFileChange"
    />
    <p v-if="compressing" class="mt-1.5 text-xs text-amber-400 flex items-center gap-1.5">
      <i class="bi bi-arrow-clockwise animate-spin"></i> Wird komprimiert…
    </p>
    <p v-else-if="info" class="mt-1.5 text-xs flex items-center gap-1" :class="error ? 'text-red-400' : 'text-green-400'">
      <i :class="error ? 'bi bi-exclamation-circle' : 'bi bi-check-circle'"></i> {{ info }}
    </p>
  </div>
</template>

<script setup lang="ts">
import { ref, computed, watch } from 'vue'
import { compressImage, fmt } from '../../composables/useImageCompressor'

const MAX_BYTES = 10 * 1024 * 1024

const props = defineProps<{
  modelValue: File | null
  preview?: string
}>()

const emit = defineEmits<{
  'update:modelValue': [File | null]
}>()

const localPreview = ref<string | null>(null)
const compressing = ref(false)
const info = ref('')
const error = ref(false)

const currentPreview = computed(() => localPreview.value || props.preview || null)

watch(() => props.modelValue, val => {
  if (!val) {
    localPreview.value = null
    info.value = ''
    error.value = false
  }
})

async function onFileChange(e: Event) {
  const input = e.target as HTMLInputElement
  const file = input.files?.[0] ?? null
  info.value = ''
  error.value = false

  if (!file) {
    emit('update:modelValue', null)
    localPreview.value = null
    return
  }

  if (file.size <= MAX_BYTES) {
    emit('update:modelValue', file)
    localPreview.value = URL.createObjectURL(file)
    return
  }

  // Datei zu groß → automatisch komprimieren
  compressing.value = true
  try {
    const result = await compressImage(file, MAX_BYTES)
    emit('update:modelValue', result.file)
    localPreview.value = URL.createObjectURL(result.file)
    info.value = `Komprimiert: ${fmt(result.originalSize)} → ${fmt(result.compressedSize)}`
  } catch (err: any) {
    info.value = err.message ?? 'Komprimierung fehlgeschlagen.'
    error.value = true
    input.value = ''
    emit('update:modelValue', null)
    localPreview.value = null
  } finally {
    compressing.value = false
  }
}
</script>

// frontend/src/lib/components/admin/ImageUpload.svelte
<script lang="ts">
  import { compressImage, fmt } from '$lib/utils/imageCompressor'

  const MAX_BYTES = 10 * 1024 * 1024
  let { file = $bindable<File | null>(null), preview = '' }: { file?: File | null; preview?: string } = $props()

  let localPreview  = $state<string | null>(null)
  let compressing   = $state(false)
  let info          = $state('')
  let hasError      = $state(false)

  const currentPreview = $derived(localPreview || preview || null)

  $effect(() => {
    if (!file) { localPreview = null; info = ''; hasError = false }
  })

  async function onFileChange(e: Event) {
    const input = e.target as HTMLInputElement
    const picked = input.files?.[0] ?? null
    info = ''; hasError = false

    if (!picked) { file = null; localPreview = null; return }

    if (picked.size <= MAX_BYTES) {
      file = picked; localPreview = URL.createObjectURL(picked); return
    }

    compressing = true
    try {
      const r = await compressImage(picked, MAX_BYTES)
      file = r.file
      localPreview = URL.createObjectURL(r.file)
      info = `Komprimiert: ${fmt(r.originalSize)} → ${fmt(r.compressedSize)}`
    } catch (err: any) {
      info = err.message ?? 'Komprimierung fehlgeschlagen.'
      hasError = true
      input.value = ''
      file = null; localPreview = null
    } finally { compressing = false }
  }
</script>

<div>
  {#if currentPreview}
    <div class="mb-2">
      <img src={currentPreview} class="h-24 w-24 object-cover rounded-lg" style="border: 1px solid rgba(255,255,255,0.12)" alt="Vorschau" />
    </div>
  {/if}
  <input
    type="file"
    accept="image/jpeg,image/png,image/webp"
    disabled={compressing}
    class="admin-file-input block w-full text-sm cursor-pointer"
    style="color: var(--ink-1)"
    onchange={onFileChange}
  />
  {#if compressing}
    <p class="admin-info mt-1.5 text-xs flex items-center gap-1.5">
      <i class="bi bi-arrow-clockwise animate-spin"></i> Wird komprimiert…
    </p>
  {:else if info}
    <p class="mt-1.5 text-xs flex items-center gap-1" class:admin-success={!hasError}
       style={hasError ? 'color: var(--neon-magenta)' : ''}>
      <i class="bi" class:bi-check-circle={!hasError} class:bi-exclamation-circle={hasError}></i>
      {info}
    </p>
  {/if}
</div>
